FROM httpd

RUN set -eux; \
	apt-get update; \
	apt-get -y install apache2-dev flex bison libxml2-dev libjpeg-dev libpng-dev libxpm-dev libpq-dev libicu-dev libfreetype6-dev libldb-dev; \
	apt-get clean
#RUN apt-get -y install apache2 apache2-dev flex bison libxml2-dev libcurl4-openssl-dev libjpeg-dev libpng-dev libxpm-dev libpq-dev libicu-dev libfreetype6-dev libldap2-dev libxslt-dev libldb-dev curl
#RUN apt-get -y install apache2 apache2-dev flex bison libxml2-dev libjpeg-dev libpng-dev libxpm-dev libpq-dev libicu-dev libfreetype6-dev libldb-dev
#RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so
#RUN apt-get install build-essential


RUN mkdir -p /usr/local/src/ /usr/local/apache2/conf/conf.d/
ADD http://de2.php.net/get/php-5.6.36.tar.bz2/from/this/mirror /usr/local/src/php-5.6.36.tar.bz2

#FROM apache-php-5.6.32-base:latest

RUN set -eux; \ 
	cd /usr/local/src/; \
	tar xjf php-5.6.36.tar.bz2; \
	rm php-5.6.36.tar.bz2; \
	cd /usr/local/src/php-5.6.36; \
	./configure \
	--prefix=/usr/local/php5.6.36 \
        --with-apxs2=/usr/local/apache2/bin/apxs \
	--with-gd \
	--with-jpeg-dir=/usr/lib64 \
	--with-png-dir=/usr/lib64 \
	--with-pgsql \
	--with-freetype-dir=/usr/lib64 \
	--with-zlib \
	--enable-gd-native-ttf \
	--enable-mbstring; \
   	make; \
	make install; \
        libtool --finish /usr/local/src/php-5.6.36/libs; 
#\
#	rm -r /usr/local/src/php-5.6.36;

COPY php.ini /usr/local/php5.6.36/lib/
COPY php.conf /usr/local/apache2/conf/conf.d/
